@baseUrl=http://localhost:3000/api/auth

### Register user
POST {{baseUrl}}/register
Content-Type: application/json

{
  "name": "test",
  "email": "test@test.com",
  "password": "test123"
}

### Login user
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "test123"
}